language: node_js
node_js:
- 12
- 10
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npm run semantic-release
branches:
  only:
  - master
env:
  global:
  - secure: jV4MQsl6vTlrT1UeJq1+edEhlemi2eyZETX839r8SeTeXdHToIALhhJq3d8Y+sfKmUWL+Zx11uU4JfO5gZjxR/JilTB2gkiSUkQ6emL2UevV+MnEKBdC0QDGZcQT79M8uO3cwzFZYROcMIHz/TmBKYQutCnfE7SziaUD43q3/DhN7w1DM2T4wop/O/ofnjOaV2YzggX8ReWdaI/zSjAEKU/F+NJA9uyUtigrMtK/dRxckr50w7uYWLM/a4xJwUtLtBE9/a/iKYhjulsPTpxKAgZG/WNf9Ojql9qYlsNKv9Oa878stdo4u4w8p6WfaspYKgBS+yD6aAVviUdDoGIvadCvLKh7sBrRkQI7HDsGZxuXAOGYEp3znwUgBEGua/g7oU4vDGg2LcRB4yd9rl7vxepG1f6/5hQr6kVxkFAh5So7E2313H92Gn0CC5kVKVFTsMeZq/nbje/4ym7cwZObd7eShmqTgLalEDYh68bDhN+yBn0cOO66P1Z4jtqm/qiM49IcpghjbJps4iXS2Phn68tMYgHURRHbL5sCdZRKNi07OEoYAxEsePcJJJfmYqwU1RFmolTyTzZHNa3q51QBs8/phjRJjWv48U8T7RCbgiRApTwQPtNHZVl9fMAw0Uf9/6w1Z+7XW+FL1PYAzxAt4tPYFpG50dCRWWr3MuPHXwM=
  - secure: qferxS6efBVXH8j4ik9mN++r3bM42RobPf7O1PtEDbTXCAh3is9VVO/Sk3RkTxjPIg8Rcgznp8ltE36RWjGY15S4b3pu6KTX9tPFg6OAda/1FAtKVLww+ZWG4E5AAUV/ind+amAVUrSSu3UHmhHmvBFLrtA7BAxUVYpPEOjArU5w+5iHL4sLkt63aseI4V7JlVl9dh3jZbvYoxl+JxAUTuRDaxvmr1QDK4tJZRPwfT8QJtY17kE1mYbhK7SXy206RsknhO8arZi0nPtaDbLa4SoZ1p992dpmDDLTPuUMJ0/vw9ER0DQPH+Xan8egkd97CXIRsxPUBq4V3GmLcCJ7MLMj5JwH/u6bcBXlLg3M/HKKFpOizxcUz7eWeXXlh7xcuAvPh4vNEW6HdaF/65b1+cGDpdEueY6ZYIDDyaslGjBMr+tQMPPsac5h9UmReNR5pOKqtJXPUg5uPReOGz3kU+1TW7UJXK1i0/hWz/65F59ZtYeSWUL2x8618A5RXb3g6sR6xz4z2yQSV6MSEO4Sd0ay5cHIHIV9OpGMNTm90TJ1Vrojb2cARguIZrKSK+22koK8urvr2XxBvdKnoZQ306hdVBBsw/4fhTqEs5DiV0CjCC2Db2aGcMye4dfUKia0gQlsZqRtVIYiNju8t2u3Nq9U9rLc3jdTZH75b5GNErc=
